# Generated by Django 5.0.3 on 2024-03-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_list_title_list_composite_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='name',
        ),
    ]
